export enum APP_ACTION {
    ADD_TO_CART = 'ADD_TO_CART',
    SUBTRACT_FROM_CART = 'SUBTRACT_FROM_CART',
    DELETE_FROM_CART = 'DELETE_FROM_CART',
    UPDATE_QUANTITY = 'UPDATE_QUANTITY',
    CLEAR_CART = 'CLEAR_CART',

    LOGIN = 'LOGIN',
    LOG_OUT = 'LOG_OUT',
}